[package]
name = "nexus_singularity"
version = "0.2.2"
edition = "2021"

[dependencies]
axum = { version = "0.7", features = ["ws"] }
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.5", features = ["fs", "cors"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.11", features = ["json"] }
anyhow = "1.0"
# The Local AI Muscle
ort = { version = "2.0.0-rc.11", default-features = false, features = ["load-dynamic"] }
once_cell = "1.21.3"
chrono = { version = "0.4.43", features = ["clock"] }
rand = "0.9.2"

[features]
default = ["remote-ai", "local-onnx"]
remote-ai = []
local-onnx = []
